[supervisord]
nodaemon=true          ; run in foreground as PID 1
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a local socket

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

; Sidecar Process
[program:sidecar]
command=/root/.sidecar/sidecar
directory=/root/.sidecar
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/sidecar.err.log
stdout_logfile=/var/log/supervisor/sidecar.out.log


; Example of a managed app (disabled by default)
; [program:main-app]
; command=/path/to/main-app --port 8080
; autostart=false
; autorestart=true
; stderr_logfile=/var/log/main-app.err.log
; stdout_logfile=/var/log/main-app.out.log

; Allow hot-plugging new processes smoothly
[include]
files = /etc/supervisor/conf.d/*.conf
